---
title: "Test"
author: "Pengyuan Su (ps3195)"
date: "11/20/2020"
output: html_document
---

```{r echo=FALSE,warning=FALSE,message=FALSE}
library(tidyverse)
library(plotly)

knitr::opts_chunk$set(
  #fig.width = 6,
  #fig.asp = .6,
  #out.width = "90%",
  echo = F,
  warning = F
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Import data (Mainly focus on publisher and their console)

```{r}
path = "data/vgchartz.csv"
```

```{r}
data = 
  read_csv(path) %>% 
  janitor::clean_names() %>% 
  separate(release_date, into = c("year", "month", "day")) %>% 
  select(title, console, year, publisher, total_sale) %>% 
  mutate(year = as.numeric(year),
         publisher = factor(publisher),
         console = factor(console))
```

# Plot for year and sale, Plot for year and console

*year of game vs sale*
```{r}
year_sale = 
  data %>% 
  group_by(year) %>% 
  summarize(
    yearsale = sum(total_sale)
  ) 
  
plot_year_sale =
  year_sale %>% 
  plot_ly(x = ~year, y = ~yearsale, type = "bar")
plot_year_sale


```

*test for the normality*

```{r}
sales = pull(year_sale, yearsale)
shapiro.test(sales)
```

*year vs console*

```{r}

plot_year_console =
  data %>% 
  mutate(text_label = str_c("Game:", title, "\nrelease year:", year, "\nPublisher:", publisher, "\nSales: ", total_sale)) %>% 
  plot_ly(x = ~year, y = ~console, color = ~console, text = ~text_label, type = "box")
plot_year_console

```


# Publisher (TOP 10)

```{r}
publisher =
  data %>% 
  group_by(publisher) %>% 
  summarize(pub_sale = sum(total_sale)) %>% 
  arrange(-pub_sale) %>% 
  slice(1:10) %>% 
  mutate(
    publisher = forcats::fct_reorder(publisher, -pub_sale)
  ) 

publisher_plot_bar = 
  publisher %>% 
  ggplot(aes(x = publisher, y = pub_sale, fill = publisher)) +
  geom_bar(stat = "identity") +
  theme(
    legend.position = 'none',
    axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust = 1)
                              ) +
  labs(
    title = "Top 10 sales for Publisheer",
    x = "publisher",
    y = "sales (Million)"
  )
ggplotly(publisher_plot_bar)

publisher_plot_box = 
  data %>% 
  group_by(title) %>% 
  mutate(total_sale = sum(total_sale)) %>% 
  select(publisher, total_sale) %>%
  distinct() %>% 
  filter(publisher %in% c("Nintendo", "Activision", "Electronic Arts", "Sony Computer Entertainment", "EA Sports", "Ubisoft", "THQ", "Sega", "Capcom", "Rockstar Games")) %>% 
  mutate(publisher = fct_relevel(publisher, "Nintendo", "Activision", "Electronic Arts", "Sony Computer Entertainment", "EA Sports", "Ubisoft", "THQ", "Sega", "Capcom", "Rockstar Games"),
         text_label = str_c("Game:", title,"\nPublisher:", publisher, "\nSales: ", total_sale)) %>% 
  plot_ly(x = ~publisher, y = ~total_sale, text = ~text_label, type = "box") %>% 
  layout(
    xaxis = list(title = "publisher"),
    yaxis = list(title = "sales (Million)"),
    title = "publisher vs. sales"
  ) 
publisher_plot_box
```

## Select Period 2005-2015

```{r}
publisher_period =
  data %>% 
  filter(year >= 2005 & year <= 2015) %>% 
  group_by(publisher) %>% 
  summarize(pub_sale = sum(total_sale)) %>% 
  arrange(-pub_sale) %>% 
  slice(1:10) %>% 
  mutate(
    publisher = forcats::fct_reorder(publisher, -pub_sale)
  ) 

publisher_plot_bar_p = 
  publisher_period %>% 
  ggplot(aes(x = publisher, y = pub_sale, fill = publisher)) +
  geom_bar(stat = "identity") +
  theme(
    legend.position = 'none',
    axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust = 1)
                              ) +
  labs(
    title = "Top 10 sales for Publisheer during 2005 ~ 2015",
    x = "publisher",
    y = "sales (Million)"
  )
ggplotly(publisher_plot_bar_p)
```


```{r}
publisher_plot_box = 
  data %>% 
  filter(year >= 2005 & year <= 2015) %>% 
  group_by(title) %>% 
  mutate(total_sale = sum(total_sale)) %>% 
  select(publisher, total_sale) %>%
  distinct() %>% 
  filter(publisher %in% c("Nintendo", "Activision", "Electronic Arts", "Sony Computer Entertainment", "EA Sports", "Ubisoft", "THQ", "Sega", "Capcom", "Rockstar Games")) %>% 
  mutate(publisher = fct_relevel(publisher, "Nintendo", "Activision", "Electronic Arts", "Sony Computer Entertainment", "EA Sports", "Ubisoft", "THQ", "Sega", "Capcom", "Rockstar Games"),
         text_label = str_c("Game:", title,"\nPublisher:", publisher, "\nSales: ", total_sale)) %>% 
  plot_ly(x = ~publisher, y = ~total_sale, text = ~text_label, type = "box") %>% 
  layout(
    xaxis = list(title = "publisher"),
    yaxis = list(title = "sales (Million)"),
    title = "publisher vs. sales"
  ) 
publisher_plot_box
```

## Focus on Nitendo

```{r}
nintendo =
  data %>% 
  filter(year >= 2005 & year <= 2015 & publisher == "Nintendo" & console != "VC") 
   
  
nintendo_console =
  nintendo %>% 
  group_by(console) %>% 
  ggplot(aes(x = console, y = total_sale, fill = console)) +
  geom_boxplot()

ggplotly(nintendo_console)
```

### Nintendo Console

```{r}
console = tibble(
  console = c("Game & Watch", "NES", "Game Boy (GB)", "SNES", "Virtual Boy", "N64", "GameCube (GC)", "Game Boy Advance", "DS", "Wii", "Nintendo 3DS (3DS)", "Will U (WiiU)", "NES", "Switch (NS)"),
  time = c("1980-1991", "1983-1995", "1989-2003", "1990-1998", "1995-1996", "1996-2003", "2001-2007", "2001-2008", "2004-2014", "2006-2013", "2011-", "2012-2016", "2016-2017", "2017-")
)

knitr::kable(console)
```

### games on each Nintendo Console during 2005-2015 
```{r}
count = count(nintendo, console)

knitr::kable(count)

```



```{r}
console_sales =
  nintendo %>% 
  select(console, total_sale) %>% 
  mutate(console = factor(console)) %>% 
  pivot_wider(
    names_from = "console",
    values_from = "total_sale"
  )
WiiU = c(2.42, 1.26, 1.24, 0.86, 0.36, 0.19, 0.05, 2.08, 5.07, 2.00, 0.86, 0.29, 5.62, 5.01, 3.45, 1.71, 1.52, 0.58, 1.41, 0.02, 7.69, 0.84, 4.71, 0.80, 0.54, 0.38, 1.23)
  
`3DS` = c(1.74, 1.28, 1.15, 0.50, 0.33, 0.21, 0.11, 0.03, 2.50, 0.25, 5.44, 3.57, 2.00, 1.24, 0.82, 8.32, 0.50, 0.49, 0.27, 11.56, 11.33, 2.13, 2.05, 1.66, 0.32, 0.01, 1.84, 0.81, 0.56, 0.44, 0.08, 15.49, 16.13, 12.73, 2.55, 2.41, 2.33, 2.10, 1.41, 1.41, 1.31, 1.09, 0.56, 0.42, 0.09, 0.03, 0.96, 10.90, 5.88, 4.15, 3.41, 0.96, 0.94, 0.75, 0.01, 1.00, 0.49, 0.12, 0.22)  

Wii = c(1.36, 0.47, 0.44, 0.11, 0.07, 0.76, 0.11, 7.18, 3.96, 1.18, 1.06, 0.33, 0.06, 0.05, 0.05, 0.01, 12.91, 0.26, 28.92, 8.41, 8.30, 3.79, 0.92, 0.73, 0.48, 0.19, 28.51, 11.40, 7.57, 6.50, 3.73, 2.62, 2.09, 1.66, 1.15, 0.69, 0.60, 2.89, 35.98, 0.62, 0.53, 0.28, 1.59, 0.92, 0.03, 0.01, 4.98, 1.79, 0.61, 0.43, 4.65, 0.87, 82.65, 32.90, 22.70, 21.81, 2.59, 2.08, 1.89, 1.46, 0.64, 0.61, 0.49, 0.34)

GBA = c(0.11, 1.42, 0.98, 0.77, 0.65, 0.24, 0.05, 0.74, 0.33, 0.01, 0.01, 6.41, 2.06, 1.13, 0.40, 0.29, 0.28, 0.26, 0.03, 0.52, 0.03, 0.89)

DS = c(0.10, 0.05, 0.01, 5.20, 5.09, 3.95, 3.32, 3.28, 2.68, 1.27, 0.54, 0.29, 0.22, 0.19, 0.14, 0.11, 0.74, 0.55, 0.16, 20.16, 15.29, 8.93, 6.63, 3.83, 3.67, 3.45, 3.33, 3.13, 2.52, 1.71, 0.73, 0.67, 0.61, 0.59, 0.56, 0.52, 0.51, 0.37, 0.29, 0.27, 0.26, 0.26, 0.19, 0.16, 29.85, 2.92, 2.77, 1.94, 1.03, 1.00, 0.85, 0.72, 0.65, 0.55, 0.38, 0.22, 0.17, 2.68, 2.30, 2.11, 1.69, 1.19, 0.59, 0.55, 0.50, 0.50, 0.43, 0.33, 0.26, 0.23, 0.21, 0.19, 0.17, 0.14, 0.07, 0.05, 0.01, 23.26, 1.22, 0.77, 18.25, 15.18, 11.78, 8.16, 7.72, 5.79, 4.94, 3.77, 2.28, 2.15, 2.03, 1.73, 1.56, 1.42, 1.30, 1.29, 1.02, 0.89, 0.81, 0.67, 0.53, 0.48, 0.30, 0.29, 0.25, 0.17, 0.12, 0.12, 0.11, 0.09, 0.04, 0.76, 0.53, 24.68, 12.14, 2.58, 0.27, 0.06, 1.61, 0.78, 0.18, 0.16, 0.61, 0.61, 0.39, 0.27, 0.11, 0.03)

GC = c(1.59, 0.39, 0.15, 1.57, 0.39, 1.34, 1.25, 0.54, 0.10, 1.08, 0.47, 0.06, 1.61, 1.46, 0.40)
  
  #nintendo %>% 
  #select(console, total_sale) %>% 
  #filter(console == "GC") %>% 
  #pivot_wider(
  #  names_from = "console",
  #  values_from = "total_sale"
  #) %>% 
  #as.data.frame()
nin = c(WiiU, `3DS`, Wii, GBA, DS, GC)

ind = c(rep(1,length(WiiU)),rep(2,length(`3DS`)),rep(3,length(Wii)),rep(4,length(GBA)),rep(5,length(DS)), rep(6,length(GC)))

new_data = as.data.frame(cbind(nin,ind))

res <- lm(nin~factor(ind), data = new_data)

anova(res)

pairwise.t.test(new_data$nin, new_data$ind, p.adj = 'bonferroni')

res1 <- aov(nin~factor(ind), data = new_data)
TukeyHSD(res1)

plot(TukeyHSD(res1))
```



